#!/usr/bin/env bash
# Firefox Bridge for Claude — installer (Windows + Git Bash).
# Detects Firefox / Git Bash / the C# compiler / your default Firefox profile,
# wires everything up, compiles a windowless auto-start launcher, and installs
# it to run at login. Re-runnable. See uninstall.sh to undo.
set -e
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "== Firefox Bridge for Claude — install =="
echo "   source: $DIR"

# --- Firefox ---
FIREFOX="${FBC_FIREFOX:-}"
if [ -z "$FIREFOX" ]; then
  for p in "/c/Program Files/Mozilla Firefox/firefox.exe" \
           "/c/Program Files (x86)/Mozilla Firefox/firefox.exe"; do
    [ -f "$p" ] && FIREFOX="$p" && break
  done
fi
[ -z "$FIREFOX" ] && { echo "ERROR: Firefox not found. Install it, or run with FBC_FIREFOX=/path/to/firefox.exe"; exit 1; }
echo "   Firefox:  $FIREFOX"

# --- Git Bash (for the launcher) ---
GITBASH=""
for p in "/c/Program Files/Git/bin/bash.exe" "/c/Program Files (x86)/Git/bin/bash.exe"; do
  [ -f "$p" ] && GITBASH="$p" && break
done
[ -z "$GITBASH" ] && { echo "ERROR: Git for Windows (bash.exe) not found."; exit 1; }
echo "   Git Bash: $GITBASH"

# --- C# compiler (ships with .NET Framework; no SDK needed) ---
CSC="$(ls /c/Windows/Microsoft.NET/Framework64/v4.0.*/csc.exe 2>/dev/null | head -1)"
[ -z "$CSC" ] && CSC="$(ls /c/Windows/Microsoft.NET/Framework/v4.0.*/csc.exe 2>/dev/null | head -1)"
[ -z "$CSC" ] && { echo "ERROR: csc.exe (.NET Framework 4) not found."; exit 1; }
echo "   csc:      $CSC"

# --- Perl (Git Bash ships it) ---
command -v perl >/dev/null || { echo "ERROR: perl not found (comes with Git for Windows)."; exit 1; }
perl -MIO::Socket::INET -MJSON::PP -e 1 2>/dev/null || { echo "ERROR: perl is missing IO::Socket::INET / JSON::PP (both core)."; exit 1; }

# --- default Firefox profile (for the debug prefs) ---
PROFILES_INI="$APPDATA/Mozilla/Firefox/profiles.ini"
PROFILE_DIR=""
if [ -f "$PROFILES_INI" ]; then
  rel=$(perl -0777 -ne '
    my $p;
    if(/\[Install[^\]]*\][^\[]*?Default=(\S+)/s){ $p=$1 }
    if(!$p){ while(/Path=(\S*default-release\S*)/g){ $p=$1; last } }
    if(!$p){ while(/\[Profile\d+\]([^\[]*)/gs){ my $b=$1; if($b=~/Default=1/ && $b=~/Path=(\S+)/){ $p=$1; last } } }
    $p =~ s/\s+$// if $p; print $p if $p;' "$PROFILES_INI")
  if [ -n "$rel" ]; then
    case "$rel" in
      /*|[A-Za-z]:*) PROFILE_DIR="$rel" ;;
      *) PROFILE_DIR="$APPDATA/Mozilla/Firefox/$rel" ;;
    esac
  fi
fi
echo "   Profile:  ${PROFILE_DIR:-<not found — you may need to enable remote debugging manually>}"

# --- write machine config ---
cat > "$DIR/config.sh" <<EOF
# Auto-generated by install.sh — machine-specific, git-ignored.
export FBC_FIREFOX="$FIREFOX"
export FBC_PORT_BRIDGE=8765
export FBC_PORT_RDP=6000
EOF

# --- enable the localhost-only debug channel in the profile ---
if [ -n "$PROFILE_DIR" ] && [ -d "$PROFILE_DIR" ]; then
  UJS="$PROFILE_DIR/user.js"
  touch "$UJS"
  if ! grep -q 'devtools.debugger.remote-enabled' "$UJS" 2>/dev/null; then
    cat >> "$UJS" <<'EOF'
// Firefox Bridge for Claude: allow localhost-only remote debugging so the
// extension can be auto-loaded (no automation/robot flag).
user_pref("devtools.debugger.remote-enabled", true);
user_pref("devtools.debugger.prompt-connection", false);
user_pref("devtools.chrome.enabled", true);
EOF
    echo "   wrote debug prefs -> user.js"
  fi
fi

# --- generate + compile the windowless launcher ---
GITBASH_WIN="$(cygpath -w "$GITBASH")"
LAUNCH_U="$(cygpath -u "$DIR/launch.sh")"
cat > "$DIR/bridge/launcher.cs" <<EOF
// Auto-generated by install.sh. Windowless launcher: runs launch.sh via Git Bash
// with no console window. (AVG etc. allow .exe autostart; block .vbs/.ps1.)
using System.Diagnostics;
class Launcher {
  static void Main() {
    var psi = new ProcessStartInfo {
      FileName = @"$GITBASH_WIN",
      Arguments = "-l \"$LAUNCH_U\"",
      UseShellExecute = false, CreateNoWindow = true, WindowStyle = ProcessWindowStyle.Hidden
    };
    try { Process.Start(psi); } catch {}
  }
}
EOF
EXE_WIN="$(cygpath -w "$DIR/FirefoxBridgeForClaude.exe")"
CS_WIN="$(cygpath -w "$DIR/bridge/launcher.cs")"
MSYS2_ARG_CONV_EXCL='*' "$CSC" -nologo -target:winexe "-out:$EXE_WIN" "$CS_WIN"
echo "   built:    FirefoxBridgeForClaude.exe"

# --- install to Startup (auto-run at login) ---
STARTUP="$APPDATA/Microsoft/Windows/Start Menu/Programs/Startup"
mkdir -p "$STARTUP"
cp "$DIR/FirefoxBridgeForClaude.exe" "$STARTUP/FirefoxBridgeForClaude.exe"
echo "   autostart: installed in Startup"

echo ""
echo "Done. Starting it now..."
"$DIR/FirefoxBridgeForClaude.exe" &
echo "Firefox will open with the bridge loaded. Test with:"
echo "   bash \"$DIR/ff.sh\" ping"
echo "It also starts automatically every time you log in. To undo: bash uninstall.sh"
